on:
  push:
    tags:
      - "v*"

name: Push `matchbox_server` to Docker Hub

jobs:
  build:
    name: Login, Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: matchbox_server/Dockerfile
          tags: ${{ vars.DOCKERHUB_USERNAME }}/matchbox_server:${{github.ref_name}}
